repos:
- repo: https://github.com/pycqa/flake8.git
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-typing-imports==1.14.0]
    args: ['--max-line-length=120', '--min-python-version=3.10']
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  - id: poetry-lock
  - id: poetry-export
    args: ["-f", "requirements.txt", "-o", "./requirements.txt", "--without", "dev", "--without-hashes"]
